Feature
VuDej/Portfolio-mobile-version pull request #2
Opened 2021-11-24 16:32 UTC by VuDej

2021-11-24 16:42 UTC, ahmetbozaci requested changes
# STATUS: INVALID  ❌ 

### Hello @VuDej  ✋🏼 
#### I can't review your project. Your pull request has no meaningful title and summary. This is a general [requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#:~:text=Write%20a%20meaningful%20title%20for%20your%20pull%20request%20and%20always%20add%20a%20short%20summary%20of%20changes%20introduced%20in%20the%20pull%20request.). Please fill them.

#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


### Cheers and Happy coding! 💻 👏
![coding](https://media.giphy.com/media/LmNwrBhejkK9EFP504/giphy.gif)


___

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Invalid Code Review Request **Does not count** into the code reviews limit._

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_


_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mentioning me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._
___
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2021-11-24 19:40 UTC, MrBrN197 requested changes
Hi @VuDej 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
 ## To Highlight
✔Very Professionals README 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 19:40 UTC, MrBrN197 commented on index.html
> +      <nav class= 'navbar'>
- [ ] please put the navbar in a header tag. We always need to follow semantic HTML guides. 
Something like this would be nice 
something like this would be better. 
```suggestion
      <header class= 'navbar'>
```

2021-11-24 19:40 UTC, MrBrN197 commented on index.html
> +       <a href="https://www.google.com/"><i class="fa-brands fa-creative-commons-nd menu"></i></a>
- [ ] OPTIONAL you can leave the `href` attribute as simply a `#` or you can replace the `a` tag with another element insteed.
something like this would work much better.
```suggestion
       <div><i class="fa-brands fa-creative-commons-nd menu"></i></div>
```

2021-11-24 19:40 UTC, MrBrN197 commented on index.html
> +       <h1 class='name'>Dejan Vujovic</h1>
- [ ] Hi, you've done well to include the logo here. as part of the requirements please kindly ensure that the Logo has an `a` tag to link to the homepage 👍. something like this would be really nice 
```suggestion
       <a href="/"><h1 class='name'>Dejan Vujovic</h1></a>
```

2021-11-24 19:40 UTC, MrBrN197 commented on index.html
> +   <container id='wraper'>
- [ ] I understand that this section should be a container. but `container` is not a valid html tag you can use on of the valid HTML tags such as `main` or `div`. it is crucial to follow proper HTML semantics 👍. 
Something like this would be better:
```suggestion
   <main id='wraper'>
```

2021-11-24 19:40 UTC, MrBrN197 commented on index.html
> +     <h2 class='orange'> Hey There. I'm Dejan</h1>
- [ ] Hi, this looks good, the only thing I want to point out is that according to the requirements this should be an `h1` tag not an `h2`.  also I can see the the closing tag is different from the starting opening tag. please ensure your opening and closing tags always use the same name. 
something like this would be great.
```suggestion
     <h1 class='orange'> Hey There. I'm Dejan</h1>
```

2021-11-24 19:40 UTC, MrBrN197 commented on index.html
> +     <h3 class='orange' >I'm Software Developer</h2>
- [ ] Hi, you've done really well implementing the sub heading. however as per the requirements ensure that you are following the same fonts and **colors**.
## You Design
![image](https://user-images.githubusercontent.com/18730106/143301073-c9096c00-91a4-458e-af3c-ac21df54a188.png)
## Figma Design 
![image](https://user-images.githubusercontent.com/18730106/143301113-d2f6c348-5b9f-4987-b42b-89de23b1b013.png)

2021-11-24 19:40 UTC, MrBrN197 commented on index.html
> +    </section>
- [ ] You've implemented this section correctly in terms of HTML semantics and it is well organized 👏. However when I look at the browser it doesn't match the Figma design. please take your time to match the figma design to as close as possible. 
- [ ] Please also ensure that the design looks correct when viewing it on a mobile.
## You Design 
![image](https://user-images.githubusercontent.com/18730106/143302251-c5da7504-92d4-4278-b296-b02c5a31a56f.png)

## Figma Design 
![image](https://user-images.githubusercontent.com/18730106/143302328-aa6384ae-3c1d-4d91-809f-60d04c37b2c0.png)

2021-11-24 19:40 UTC, MrBrN197 commented on style.css
> +    background: linear-gradient(to left, #bdc3c7, #2c3e50);
- [ ] Please ensure that you have the same background as used in the Figma. You are missing the background image and instead are using a linear-gradient.
## Your Design 
![image](https://user-images.githubusercontent.com/18730106/143302881-02f73eb1-92b1-494e-8230-a77ced1e20dc.png)
## Figma Design
![image](https://user-images.githubusercontent.com/18730106/143302754-f58f72a1-f325-4658-a978-c4f993d5fd9b.png)

2021-11-24 19:44 UTC, MrBrN197 reviewed
## Hi @VuDej 👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that You have then closed & re-opened your request and now it is a draft. Your linters don't seem to be functional as well

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-24 22:30 UTC, leolpaz requested changes
Hi @VuDej , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a draft instead of a ready to review pull request, follow this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) to change the stage of a pull request, then make sure the Linter is working before asking for another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-25 01:07 UTC, carlos-ssh requested changes
# 🦺 🚧 🚥 CHANGES REQUIRED 🚥 🚧 🦺
#

Hi @VuDej , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._ 


![changesrequested](https://user-images.githubusercontent.com/22258274/139840240-ea0d564a-492a-44e3-87af-8d5830ab0d6d.gif)
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 01:07 UTC, carlos-ssh commented on index.html
> +    <link rel="stylesheet" href="style.css">
- background aren't displaying kindly fix it.

2021-11-25 01:25 UTC, merged